dist: trusty
sudo: required
language: c
 
compiler:
- gcc

before_install:
- sudo apt-get update
- sudo apt-get install libpng12-dev
- sudo apt-get install binutils-mingw-w64-i686 gcc-mingw-w64-i686

install:
- ./autogen.sh
- ./configure --with-tests && make
- sudo make install
- mkdir build && cd build
- cmake .. -DWITH_TESTS=yes -DBUILD_SHARED_LIBS=on && make
- DESTDIR=$PWD/install make install

before_script:
- export CC=i686-w64-mingw32-gcc

script:
- cd $TRAVIS_BUILD_DIR/tests
- ./test_all.sh
- cd $TRAVIS_BUILD_DIR/build/tests
- cp $TRAVIS_BUILD_DIR/tests/frame ./
- make test
